title: simple systemd linux container services management
description: easy command line docker services management on linux with systemd
remote_theme: https://github.com/JV-conseil/jekyll-theme-read-the-docs
